### ISSUE TITLE
One-click-install z Lebedy

### ISSUE THREAD

**Issue by MCBlesk** [skaut/crdm-modern#278]
Tato šablona nejde automaticky nainstalovat z Lebedy. Výsledek je jen prázdná bílá stránka. Nemám k tomu moc užitečných insightů. :(

**Comment by marekdedic** [comment]
Ahoj,
díky za info, koukneme na to.

Mlha

**Comment by sinacek** [comment]
Díky za upozornění, teďka jsem to opravil.
